env: dev
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: ffx10101fsn
  rabbitmq:
    username: guest
    password: sq144238
    port: 5672
    host: 47.102.97.1
girl:
  name: Yuna
  age:  20
