env: dev1
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: ffx10101fsn
  application:
    name: order
server:
  port: 8082

girl:
  name: Yuna
  age:  18
